//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2C.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class HazırDeger
    {
        public int HazırDegerId { get; set; }
        public string HazırDegerName { get; set; }
        public Nullable<int> HazırVaryantId { get; set; }
    
        public virtual HazırVaryant HazırVaryant { get; set; }
    }
}
