//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2C.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Varyants = new HashSet<Varyants>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
    
        public virtual ICollection<Varyants> Varyants { get; set; }
    }
}
