//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2C.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Varyants
    {
        public Varyants()
        {
            this.VaryantDegerler = new HashSet<VaryantDegerler>();
        }
    
        public int VaryantId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> HazırVaryantId { get; set; }
    
        public virtual HazırVaryant HazırVaryant { get; set; }
        public virtual Products Products { get; set; }
        public virtual ICollection<VaryantDegerler> VaryantDegerler { get; set; }
    }
}
