//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _12Mart2022.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;

    public partial class Personel
    {
        public int Id { get; set; }

        [Display(Name = "Departman Adı")]
        [Required(ErrorMessage = "Lütfen bir departman seçiniz!")]
        public Nullable<int> DepartmanId { get; set; }
        [Required(ErrorMessage = "Lütfen adınızı giriniz")]
        public string Ad { get; set; }
        [Required(ErrorMessage = "Lütfen soy adınızı giriniz")]
        public string Soyad { get; set; }

        [Display(Name = "Maaş")]
        [Required(ErrorMessage = "Lütfen maaşınızı giriniz")]
        [Range(999, 19999, ErrorMessage = "Lütfen 1000 ve 20.000 arasında bir maaş giriniz!")]
        public Nullable<short> Maas { get; set; }

        [Display(Name = "Doğum Tarihi")]
        [Required(ErrorMessage = "Lütfen Doğum tarihinizi giriniz")]
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        [Required(ErrorMessage = "Lütfen cinsiyetinizi giriniz")]
        public bool Cinsiyet { get; set; }

        [Display(Name = "Evlilik Durumu")]

        public bool EvliMi { get; set; }

        public virtual Departman Departman { get; set; }
    }
}
